[package]
name = "benzene"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
winit = "0.30.12"
image = "0.25.6"
memoffset = "0.9.1"
nalgebra = "0.34.0"
rand = "0.9.2"
tobj = "4.0.3"
chrono = "0.4.42"
